/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"

void clock_init()
{
	// Enable clock GPIOA
	RCC_GPIOA_CLK_EN();

	// Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_init()
{
	GPIO_PinConfig_t pin;

	// A1 floating input mode
	pin.GPIO_mode = GPIO_INPUT_FLO_MODE;
	pin.GPIO_PinNUmber = GPIO_PIN_1;

	MCAL_GPIO_init(GPIOA, &pin);
	/* ################################### */

	// B1 push pull output mode
	pin.GPIO_mode = GPIO_OUTPUT_PP_MODE;
	pin.GPIO_OutputSpeed = GPIO_SPEED_10M;
	pin.GPIO_PinNUmber = GPIO_PIN_1;

	MCAL_GPIO_init(GPIOB, &pin);
	/* ################################### */

	// A13 floating input mode
	pin.GPIO_mode = GPIO_INPUT_FLO_MODE;
	pin.GPIO_PinNUmber = GPIO_PIN_13;

	MCAL_GPIO_init(GPIOA, &pin);
	/* ################################### */

	// B13 push pull output mode
	pin.GPIO_mode = GPIO_OUTPUT_PP_MODE;
	pin.GPIO_OutputSpeed = GPIO_SPEED_10M;
	pin.GPIO_PinNUmber = GPIO_PIN_13;

	MCAL_GPIO_init(GPIOB, &pin);
}

void GPIO_Deinit()
{
	MCAL_GPIO_DeInit(GPIOA);
	MCAL_GPIO_DeInit(GPIOB);
}


void my_delay(uint32_t time)
{
	uint32_t i,j;

	for(i = 0; i < time; i++)
	{
		for(j = 0; j < 255; j++);
	}
}

int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		if ( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET ) // single pressing
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);

			while ( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET );
		}

		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_SET ) // multi pressing
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}

		my_delay(1);
	}
}
