/* ADC PreScaler Options:
 * 1- ADC_2_PRESCALER
 * 2- ADC_4_PRESCALER
 * 3- ADC_8_PRESCALER
 * 4- ADC_16_PRESCALER
 * 5- ADC_32_PRESCALER
 * 6- ADC_64_PRESCALER
 * 7- ADC_128_PRESCALER
 */
#define ADC_PRESCALER		ADC_64_PRESCALER

/* ADC Adjust Options:
 * 1- ADC_LEFT_ADJSUT
 * 2- ADC_RIGHT_ADJSUT
 */
#define ADC_ADJUST			ADC_RIGHT_ADJSUT

#endif /* MADC_CONFIG_H_ */
