/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "platform_types.h"

// RCC reg
#define RCC_BASE 	0x40021000
#define GPIOA_BASE 	0x40010800

// GPIOA register
#define RCC_APB2ENP *(vuint32_t *)(RCC_BASE+0x18)
#define GPIOA_CRH 	*(vuint32_t *)(GPIOA_BASE+0x04)
#define GPIOA_CRL 	*(vuint32_t *)(GPIOA_BASE+0x00)
#define GPIOA_ODR	*(vuint32_t *)(GPIOA_BASE+0x0C)

//bit field
#define RCC_IOPAEN   2
#define GPIOA_CRHEN  21
#define GPIOA13  	 13
#define RCC_AFIOEN	 0

// EXTI0
#define EXTI_BASE	0x40010400
// mask register
#define EXTI_IMR	*(vuint32_t *)(EXTI_BASE+0x00)
// Rising trigger selection register
#define EXTI_RTSR	*(vuint32_t *)(EXTI_BASE+0x08)
// Pending register
#define EXTI_PR		*(vuint32_t *)(EXTI_BASE+0x14)

// AFIO
#define AFIO_BASE		0x40010000
// External interrupt configuration register 1
#define AFIO_EXTICR1	*(vuint32_t *)(AFIO_BASE+0x08)

// NVIC cpu Cortex M3
#define NVIC_EXTIE0	*(vuint32_t *)(0xE000E100)


void clock_init()
{
	// Enable clock GPIOA
	RCC_APB2ENP |= (1<<RCC_IOPAEN);

	// Bit 0 AFIOEN: Alternate function I/O clock enable
	RCC_APB2ENP |= (1<<RCC_AFIOEN);
}

void GPIOA_init()
{
	// pin13 port A output pin
	GPIOA_CRH &=0xff0fffff;
	GPIOA_CRH |=(1<<GPIOA_CRHEN);

	// PinA 0 input floating to made it interrupt pin so we need it input
	GPIOA_CRL |= (1<<2);
}

int main(void)
{
	clock_init();
	GPIOA_init();
	// made configurations

	// EXTI0 configuration for Port A0
	AFIO_EXTICR1 = 0;
	// Enable rising edge
	EXTI_RTSR |= (1<<0);


	// then at least enable INT
	// Enable EXTI line 0 (mask 1)
	EXTI_IMR |= (1<<0);

	// Enable NVIC IRQ for EXTI0 found in CPU Cortex M3
	NVIC_EXTIE0 |= (1<<6);

	while(1);
}

void EXTI0_IRQHandler(void)
{
	// IRQ is happened EXTI0 ==> PORTA pin0 _|- rising edge
	// toggle led pin A 13
	GPIOA_ODR ^=(1<<GPIOA13);

	// clear pending register for line 0
	EXTI_PR |= (1<<0);
}
