/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "Stm32_F103C6_I2C_driver.h"
#include "EEPROM.h"

void clock_init()
{
	// Enable clock GPIOA, GBIOB, AFIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void my_delay(uint32_t time)
{
	uint32_t i,j;

	for(i = 0; i < time; i++)
	{
		for(j = 0; j < 255; j++);
	}
}

int main(void)
{
	clock_init();

	//Test case 1
	uint8_t data[]    = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};
	uint8_t buffer[7] = {0};

	HAL_EEPROM_Init();
	HAL_EEPROM_Write_NBytes(0xAF, data, 7);
	HAL_EEPROM_Read_NBytes(0xAF, buffer, 7);

	//Test case 2
	data[0] = 0xA;
	data[1] = 0xB;
	data[2] = 0xC;
	data[3] = 0xD;

	HAL_EEPROM_Write_NBytes(0xFFF, data, 4);
	HAL_EEPROM_Read_NBytes(0xFFF, buffer, 4);

	while(1)
	{

	}
}
